---
name: Compile PDFs
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get install -y imagemagick texlive-full
      - name: Compile
        run: make resume.pdf
      - name: Upload Resume
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resume.pdf
            resume-0.png
            resume-1.png
